name: Auto merge PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlabeled
  workflow_dispatch:

jobs:
  enable-automerge:
    name: Enable GitHub auto-merge
    if: >-
      github.event.action != 'unlabeled' &&
      contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash

  disable-automerge:
    name: Disable GitHub auto-merge
    if: github.event.action == 'unlabeled' && github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Disable auto-merge
        uses: peter-evans/disable-pull-request-automerge@v3
