name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy site to Vercel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Verify Vercel secrets are available
        id: secrets-check
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_ORG_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "Secrets for Vercel deployment are not fully configured."
            echo "configured=false" >> "$GITHUB_OUTPUT"
          else
            echo "configured=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check out repository
        if: steps.secrets-check.outputs.configured == 'true'
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: steps.secrets-check.outputs.configured == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        if: steps.secrets-check.outputs.configured == 'true'
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Deploy with Vercel
        if: steps.secrets-check.outputs.configured == 'true'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          vercel deploy --prod --token="$VERCEL_TOKEN"

      - name: Skip deployment (secrets missing)
        if: steps.secrets-check.outputs.configured != 'true'
        run: |
          echo "Skipping Vercel deployment because secrets are missing."
